-- ============================================================
-- VisionConnect Job Portal — Database Schema
-- Designed for accessibility-first job matching platform
-- ============================================================
-- Users table: stores all registered users across all roles
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('seeker', 'employer', 'admin')),
    is_approved INTEGER DEFAULT 1,        -- admin can ban users
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
-- Profiles: extended info for job seekers
-- disability_type is optional — user decides whether to share
CREATE TABLE IF NOT EXISTS profiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE NOT NULL,
    bio TEXT DEFAULT '',
    skills TEXT DEFAULT '',               -- comma-separated skills
    education TEXT DEFAULT '',
    disability_type TEXT DEFAULT '',      -- optional, user-controlled disclosure
    resume_path TEXT DEFAULT '',          -- path to uploaded resume file
    phone TEXT DEFAULT '',
    location TEXT DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- Jobs: postings created by employers
CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employer_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT DEFAULT '',
    job_type TEXT DEFAULT 'full-time' CHECK(job_type IN ('full-time', 'part-time', 'internship', 'remote', 'contract')),
    description TEXT NOT NULL,
    requirements TEXT DEFAULT '',
    salary_range TEXT DEFAULT '',
    is_approved INTEGER DEFAULT 0,        -- requires admin approval
    is_active INTEGER DEFAULT 1,
    accessibility_features TEXT DEFAULT '', -- workplace accessibility info
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employer_id) REFERENCES users(id) ON DELETE CASCADE
);
-- Applications: tracks job seeker applications
CREATE TABLE IF NOT EXISTS applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL,
    seeker_id INTEGER NOT NULL,
    status TEXT DEFAULT 'applied' CHECK(status IN ('applied', 'reviewed', 'shortlisted', 'rejected', 'hired')),
    cover_letter TEXT DEFAULT '',
    is_quick_apply INTEGER DEFAULT 0,     -- 1 = used Quick Apply feature
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (seeker_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(job_id, seeker_id)             -- prevent duplicate applications
);
-- Resumes: structured resume data generated by the AI Resume Builder
CREATE TABLE IF NOT EXISTS resumes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE NOT NULL,
    resume_data TEXT DEFAULT '{}',        -- JSON blob of structured resume
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_jobs_employer ON jobs(employer_id);
CREATE INDEX IF NOT EXISTS idx_jobs_approved ON jobs(is_approved, is_active);
CREATE INDEX IF NOT EXISTS idx_applications_job ON applications(job_id);
CREATE INDEX IF NOT EXISTS idx_applications_seeker ON applications(seeker_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);